//! Public SHA-256 compression constraints and their batch geometry.
//!
//! The symbolic circuit is replayed exactly once. Its local CSC matrices are
//! retained once, while independent compression batches are represented by a
//! tensor repetition over the instance coordinate.

use crate::piop::spartan::SpartanField as _;
use circuit::linear_map::CscMatrix;
use field::RingOps;
#[cfg(test)]
use field::{Fp, Uint};
use std::sync::OnceLock;

use blake3::Hasher;
use circuit::{
    constraints::ConstraintGenerator,
    sha256::{COMPRESSION_INPUT_BITS, compression_circuit},
};
use circuit::{integer_storage::IntegerTable, linear_map::CsrMatrix};
use field::{CheckedArithmetic, IntegerEmbedding};
use thiserror::Error;

use {
    crate::{
        ligerito::LOG_PACKING,
        pcs::{IntegerMatrixLayout, mod_q_num_chunks},
    },
    circuit::linear_map::binary::{
        PackedRepeatedVirtualMap, PackedSourceOrder, PackedSourceRepeatedVirtualMap,
        PreparedVirtualMap, PreparedVirtualMapError,
    },
};

use super::super::{
    SpartanField, SpartanMatrixError,
    bitz::SpartanBitzField,
    profile::{IopSecurityParams, IopSecurityProfile, Lambda100, ProfileError},
};
use super::prime::{
    SHA256_MAX_LOG_COMPRESSIONS, SHA256_MIN_LOG_COMPRESSIONS, Sha256PrimeError, Sha256PrimeProfile,
    sha256_instance_facts, validate_sha256_field_config,
};

#[cfg(feature = "bench-internals")]
use super::prime::{SHA256_FIXED_98_PRIME, fixed_98_security_params};

/// Live Bit source bits generated by one compression.
pub const SHA256_F_LIVE_BITS: usize = 7_144;
/// Source bits after adding the public constant-one coordinate.
pub const SHA256_F_BAR_LIVE_BITS: usize = SHA256_F_LIVE_BITS + 1;
/// Per-compression source width after removing the shared constant cell.
pub const SHA256_F_INSTANCE_BITS: usize = SHA256_F_BAR_LIVE_BITS - 1;
/// Live integer-assignment bits, including its leading constant one.
pub const SHA256_H_BAR_LIVE_BITS: usize = 20_457;
/// Per-compression assignment width after removing the shared constant cell.
pub const SHA256_H_INSTANCE_BITS: usize = SHA256_H_BAR_LIVE_BITS - 1;
/// Number of public words in one compression statement: state, block, output.
pub(crate) const SHA256_PUBLIC_WORDS: usize = 32;
/// Bit width of every public SHA-256 word.
pub(crate) const SHA256_PUBLIC_WORD_BITS: usize = 32;
/// Returns the local integer-assignment column for one public statement bit.
///
/// Word slots use canonical statement order: state `[0, 8)`, block `[8, 24)`,
/// then output `[24, 32)`. Bits within each word are least-significant first.
pub(crate) const fn sha256_public_h_column(word_slot: usize, bit: usize) -> usize {
    assert!(word_slot < SHA256_PUBLIC_WORDS);
    assert!(bit < SHA256_PUBLIC_WORD_BITS);

    match word_slot {
        0..8 => 1 + 32 * word_slot + bit,
        8..24 => 257 + 32 * (word_slot - 8) + bit,
        _ => 20_193 + 33 * (word_slot - 24) + bit,
    }
}

/// Returns the local committed-source column for one public statement bit.
///
/// This uses the same word and bit order as [`sha256_public_h_column`].
pub(crate) const fn sha256_public_f_column(word_slot: usize, bit: usize) -> usize {
    assert!(word_slot < SHA256_PUBLIC_WORDS);
    assert!(bit < SHA256_PUBLIC_WORD_BITS);

    match word_slot {
        0..8 => 513 + 32 * word_slot + bit,
        8..24 => 1 + 32 * (word_slot - 8) + bit,
        _ => 6_881 + 33 * (word_slot - 24) + bit,
    }
}

/// Live rank-1 constraints generated by one compression.
pub const SHA256_CONSTRAINTS: usize = 184;
/// Failures while compiling or repeating the public SHA-256 relation.
#[derive(Debug, Error)]
pub enum Sha256ConstraintError {
    /// The requested batch or packed global domain is empty or does not fit
    /// the host index type.
    #[error("SHA-256 batch geometry is invalid or too large")]
    InvalidBatchExponent,

    /// The outer instance capacity is outside the runtime-prime protocol's
    /// supported production window.
    #[error(
        "SHA-256 runtime-prime protocol requires log-instance-capacity in [4, 16], got {actual}"
    )]
    UnsupportedInstanceCapacityExponent { actual: usize },

    /// The selected security profile asks the validated UDR backend for an
    /// unsupported round-by-round target.
    #[error("SHA-256 Ligerito target must be in [64, 128] bits, got {actual}")]
    UnsupportedLigeritoTargetBits { actual: usize },

    /// The SHA virtual opening is deliberately configured to use one
    /// mod-q weight chunk, hence one merged forest.
    #[error("SHA-256 opening requires exactly one forest, got {actual}")]
    UnsupportedOpeningForestCount { actual: usize },

    /// An explicit layout asked for a row split the assignment domain does
    /// not admit (`LOG_PACKING <= t < vars` for the inner sumcheck,
    /// `15 <= t <= 15 + k` for the transposed product tensor).
    #[error(
        "SHA-256 opening layout cannot split {assignment_vars} assignment vars at {row_vars} row vars"
    )]
    InvalidOpeningRowVars {
        row_vars: usize,
        assignment_vars: usize,
    },

    /// The transposed product layout needs a power-of-two batch.
    #[error("SHA-256 transposed product layout needs a power-of-two batch, got {instances}")]
    ProductLayoutNeedsPowerOfTwoBatch { instances: usize },

    /// The selected security profile is incompatible with the single
    /// transcript-derived-prime SHA protocol.
    #[error(transparent)]
    PrimeProfile(#[from] Sha256PrimeError),

    /// Generated R1CS matrices did not prepare successfully.
    #[error(transparent)]
    Spartan(#[from] SpartanMatrixError),

    /// Generated Bit map metadata did not prepare successfully.
    #[error(transparent)]
    VirtualMap(#[from] PreparedVirtualMapError),

    /// The canonical integer-relation digest cannot encode this host shape.
    #[error("SHA-256 integer relation dimensions do not fit the canonical encoding")]
    IntegerRelationTooLarge,

    /// The security profile could not be instantiated at this shape.
    #[error(transparent)]
    Profile(#[from] ProfileError),

    #[error("invalid Ligerito configuration: {0}")]
    LigeritoConfig(String),

    /// The controlled product-layout sweep requires exactly `2^14`
    /// compressions and `7 <= t <= 28`.
    #[error(
        "unsupported SHA-256 product sweep geometry: log_compressions={log_compressions}, t={t}"
    )]
    UnsupportedProductSweepGeometry { log_compressions: usize, t: usize },

    /// The fixed field must exceed every exact Bit SHA row residual.
    #[error("the fixed 98-bit SHA prime does not exceed the exact Bit residual bound")]
    FixedPrimeResidualBound,
}

/// A q-independent SHA-256 compression relation prepared for a packed batch.
///
/// How the synthesized SHA assignment is laid out for the BitZ opening.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Sha256OpeningLayout {
    /// The production choice. Power-of-two batches of at least 128 open the
    /// product-structured residual directly, laid out as the balanced
    /// `Id_{2^r} ⊗ M` block layout: this resolves to
    /// [`Sha256OpeningLayout::ProductTransposed`] with the `row_vars` picked by
    /// `balanced_product_row_vars`, so the tensor split sits at the
    /// instantiation's `t = ceil(0.6 · n)` balance point instead of the
    /// `t = min(k, 13)` pin that put every local cell on the column axis.
    /// Smaller and non-power-of-two batches run the inner sumcheck over a
    /// balanced split capped at one forest.
    Default,
    /// Run the inner sumcheck and split the flat assignment domain as
    /// `2^row_vars` BitZ rows × `2^(vars - row_vars)` columns. Splits above
    /// the one-forest cap are allowed: the opening then carries one merged
    /// forest per mod-q weight chunk, while the read-off vector sent in the
    /// clear shrinks to `2^(vars - row_vars)` integers per chunk. The
    /// security derivation runs against the chosen split (its integer lift
    /// sums `2^t` terms, which narrows the prime interval once `t > k`).
    InnerSumcheck { row_vars: usize },
    /// Keep the direct product opening (no inner sumcheck) but lay the
    /// product tensor out instance-major, so the 15 local bits plus the low
    /// `row_vars - 15` instance bits form the `2^row_vars` BitZ rows and only
    /// the remaining high instance bits form the columns. The rank-one
    /// coefficient `eq(instance) · d[local]` factors across that split too.
    /// Power-of-two batches only; `15 ≤ row_vars ≤ 15 + k`; splits above the
    /// one-forest cap open with one forest per weight chunk.
    ProductTransposed { row_vars: usize },
}

/// The exact signed integer matrices and local Bit map are synthesized
/// once and shared by every batch. The committed source and derived assignment
/// share one constant, concatenate all live instances, and pad only their
/// complete global domains. The prover and verifier project this retained
/// relation only after the commitment-bound transcript selects a runtime prime.
#[derive(Clone, Debug)]
pub struct PreparedSha256CompressionBatch {
    local: &'static IntegerLocalRelation,
    map: PackedRepeatedVirtualMap,
    product_map: Option<PackedSourceRepeatedVirtualMap>,
    product_p_h: Option<IntegerMatrixLayout>,
    f_layout: IntegerMatrixLayout,
    h_layout: IntegerMatrixLayout,
    instances: usize,
    log_instance_capacity: usize,
    security: IopSecurityParams,
    ligerito: Option<crate::ligerito_flock::ResolvedLigerito>,
    prime_profile: Sha256PrimeProfile,
    opening_layout: Sha256OpeningLayout,
}

impl PreparedSha256CompressionBatch {
    /// Select only this batch's Ligerito opener; the enclosing target is retained.
    pub fn with_ligerito(
        mut self,
        selection: crate::ligerito_flock::LigeritoSelection,
    ) -> Result<Self, Sha256ConstraintError> {
        let resolved = selection
            .resolve(
                self.f_layout.row_vars + self.f_layout.col_vars - LOG_PACKING,
                self.security.ligerito_target_bits,
            )
            .map_err(Sha256ConstraintError::LigeritoConfig)?;
        self.security.adopt_ood_round(resolved.ood_bits())?;
        self.ligerito = Some(resolved);
        Ok(self)
    }

    pub fn ligerito_configuration(
        &self,
    ) -> Result<&crate::ligerito_flock::ResolvedLigerito, Sha256ConstraintError> {
        self.ligerito.as_ref().ok_or_else(|| {
            Sha256ConstraintError::LigeritoConfig(
                "test-only preparation has no production Ligerito policy".into(),
            )
        })
    }

    /// The assignment layout this batch was prepared with.
    pub const fn opening_layout(&self) -> Sha256OpeningLayout {
        self.opening_layout
    }

    /// BitZ geometry the opening runs against: the product view under the
    /// direct product opening, the packed assignment otherwise.
    pub fn opening_params(&self) -> &IntegerMatrixLayout {
        self.product_p_h.as_ref().unwrap_or(&self.h_layout)
    }

    /// Exact unpadded signed linear relation generated by the SHA circuit.
    ///
    /// The circuit emits its zero assertions as `0 * 0 = C h_bar`, so its
    /// generated R1CS `A` and `B` matrices are empty and this matrix is the
    /// original `C`. It has exactly [`SHA256_CONSTRAINTS`] rows and
    /// [`SHA256_H_BAR_LIVE_BITS`] columns.
    pub(crate) const fn linear_relation(&self) -> &Sha256LinearRelation {
        &self.local.linear_relation
    }

    /// Projects [`Self::linear_relation`] into the selected runtime field.
    #[allow(dead_code)]
    pub(crate) fn project_linear_relation(
        &self,
        field_config: &<SpartanBitzField as crate::piop::spartan::SpartanField>::Config,
    ) -> Result<PreparedSha256LinearRelation, Sha256ConstraintError> {
        self.local.linear_relation.project(field_config)
    }

    /// Flattens one live local constraint row in instance-major order.
    ///
    /// Unlike the compatibility R1CS path, this exact linear layout does not
    /// insert a 256-row block for each instance.
    #[allow(dead_code)]
    pub(crate) fn flat_constraint_row(&self, instance: usize, local_row: usize) -> Option<usize> {
        (instance < self.instances && local_row < SHA256_CONSTRAINTS)
            .then(|| instance * SHA256_CONSTRAINTS + local_row)
    }

    /// Flattens one local assignment column into the packed batch assignment.
    ///
    /// Local column zero is the one constant cell shared by every instance.
    /// Every other local column is placed immediately after the preceding
    /// instance, with no per-instance power-of-two padding.
    #[allow(dead_code)]
    pub(crate) fn flat_assignment_column(
        &self,
        instance: usize,
        local_column: usize,
    ) -> Option<usize> {
        if instance >= self.instances || local_column >= SHA256_H_BAR_LIVE_BITS {
            return None;
        }
        Some(if local_column == 0 {
            0
        } else {
            1 + instance * SHA256_H_INSTANCE_BITS + local_column - 1
        })
    }

    /// Number of live rows in the flat linear relation batch.
    #[allow(dead_code)]
    pub(crate) const fn linear_row_count(&self) -> usize {
        self.instances * SHA256_CONSTRAINTS
    }

    /// Number of live columns in the packed assignment shared by the batch.
    pub(crate) const fn linear_assignment_column_count(&self) -> usize {
        1 + self.instances * SHA256_H_INSTANCE_BITS
    }

    /// Canonical digest of the exact integer matrices and local Bit map.
    pub const fn integer_relation_digest(&self) -> &[u8; 32] {
        &self.local.digest
    }

    /// Repeated Bit map for the complete compression batch.
    pub const fn map(&self) -> &PackedRepeatedVirtualMap {
        &self.map
    }

    /// Proof-only local-column × instance view used to open the complete
    /// product-structured SHA residual directly. It is available exactly when
    /// the number of instances is a power of two.
    pub(crate) const fn product_map(&self) -> Option<&PackedSourceRepeatedVirtualMap> {
        self.product_map.as_ref()
    }

    /// BitZ geometry of the proof-only product assignment view.
    pub const fn product_assignment_params(&self) -> Option<&IntegerMatrixLayout> {
        self.product_p_h.as_ref()
    }

    /// Stable label for the proof-only product tensor ordering.
    pub fn product_layout_name(&self) -> Option<&'static str> {
        self.product_map.as_ref().map(|map| match map.order() {
            PackedSourceOrder::LocalMajor => "instance_rows",
            PackedSourceOrder::InstanceMajor => "local_rows",
        })
    }

    /// Number of live independent compression instances.
    pub const fn instances(&self) -> usize {
        self.instances
    }

    /// Logarithm of the power-of-two outer Spartan instance capacity.
    pub const fn log_instance_capacity(&self) -> usize {
        self.log_instance_capacity
    }

    /// BitZ geometry of the committed Bit source rows.
    pub const fn source_params(&self) -> &IntegerMatrixLayout {
        &self.f_layout
    }

    /// BitZ geometry of the synthesized Bit assignment rows.
    pub const fn assignment_params(&self) -> &IntegerMatrixLayout {
        &self.h_layout
    }

    /// Conservative maximum of
    /// `sum(|A_i|) sum(|B_i|) + sum(|C_i|)` over local constraint rows.
    /// For a Bit assignment this bounds the magnitude of every exact
    /// integer R1CS residual before reduction modulo q.
    pub fn max_boolean_residual_bound(&self) -> &field::Uint<2> {
        &self.local.max_boolean_residual_bound
    }

    /// The instantiated security parameters and their accounting.
    pub const fn security(&self) -> &IopSecurityParams {
        &self.security
    }

    pub(super) const fn prime_profile(&self) -> Sha256PrimeProfile {
        self.prime_profile
    }
}

/// Exact q-independent signed linear relation for one SHA compression.
///
/// This is the generated circuit's original `C` matrix, before either the row
/// domain or assignment domain is padded for the compatibility R1CS prover.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct Sha256LinearRelation {
    native_matrix: CscMatrix<Box<[i64]>>,
}

impl Sha256LinearRelation {
    /// Exact signed matrix in canonical CSC form.
    #[allow(dead_code)]
    pub(crate) const fn matrix(&self) -> &CscMatrix<Box<[i64]>> {
        &self.native_matrix
    }

    /// Exact coefficients in the native type used by the small-value prover.
    pub(crate) const fn native_matrix(&self) -> &CscMatrix<Box<[i64]>> {
        &self.native_matrix
    }

    /// Number of live local constraint rows (184).
    #[allow(dead_code)]
    pub(crate) const fn row_count(&self) -> usize {
        self.native_matrix.row_count()
    }

    /// Number of live local assignment columns (20,457).
    #[allow(dead_code)]
    pub(crate) const fn column_count(&self) -> usize {
        self.native_matrix.column_count()
    }

    /// Number of signed nonzero coefficients.
    #[allow(dead_code)]
    pub(crate) const fn nnz(&self) -> usize {
        self.native_matrix.nnz()
    }

    /// Projects the exact signed coefficients into a validated runtime field.
    #[allow(dead_code)]
    pub(crate) fn project(
        &self,
        field_config: &<SpartanBitzField as crate::piop::spartan::SpartanField>::Config,
    ) -> Result<PreparedSha256LinearRelation, Sha256ConstraintError> {
        validate_sha256_field_config(field_config)?;
        let matrix = project_signed_matrix(&self.native_matrix, field_config)?;
        Ok(PreparedSha256LinearRelation {
            matrix,
            field_config: field_config.clone(),
        })
    }
}

/// Runtime-field projection of the exact SHA linear relation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct PreparedSha256LinearRelation {
    matrix: CscMatrix<Box<[SpartanBitzField]>>,
    field_config: <SpartanBitzField as crate::piop::spartan::SpartanField>::Config,
}

impl PreparedSha256LinearRelation {
    /// Projected matrix in canonical CSC form.
    pub(crate) const fn matrix(&self) -> &CscMatrix<Box<[SpartanBitzField]>> {
        &self.matrix
    }

    /// Runtime field configuration used by every projected coefficient.
    #[allow(dead_code)]
    pub(crate) const fn config(
        &self,
    ) -> &<SpartanBitzField as crate::piop::spartan::SpartanField>::Config {
        &self.field_config
    }
}

#[derive(Debug)]
struct IntegerLocalRelation {
    linear_relation: Sha256LinearRelation,
    map: PreparedVirtualMap,
    digest: [u8; 32],
    max_boolean_residual_bound: field::Uint<2>,
}

static INTEGER_LOCAL_RELATION: OnceLock<IntegerLocalRelation> = OnceLock::new();

/// Prepares the q-independent public relation for
/// `2^log_compressions` independent SHA-256 compression invocations at the
/// DEFAULT security profile, [`Lambda100`] (no grinding anywhere; every
/// term this crate controls ≥ 100 bits). Use
/// [`prepare_sha256_compression_batch_with_profile`] to select
/// `Lambda128` or the historical `Sha128ReferenceSchedule`.
/// Supported exponents are [`SHA256_MIN_LOG_COMPRESSIONS`] through
/// [`SHA256_MAX_LOG_COMPRESSIONS`], inclusive.
/// Batches smaller than `2^7` use the packed inner sumcheck because the
/// local-major product opening requires at least 128 instance rows.
///
/// No runtime modulus is consulted here. The proof flow commits to the Bit
/// source rows before deriving `q` and internally projecting this relation.
pub fn prepare_sha256_compression_batch(
    log_compressions: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    prepare_sha256_compression_batch_with_profile::<Lambda100>(log_compressions)
}

/// [`prepare_sha256_compression_batch`] under an explicit
/// single-prime security profile: the profile's interval and grinding
/// schedule are instantiated here and drive the whole prove/verify path.
pub fn prepare_sha256_compression_batch_with_profile<P: IopSecurityProfile>(
    log_compressions: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    prepare_sha256_compression_batch_with_profile_and_layout::<P>(
        log_compressions,
        Sha256OpeningLayout::Default,
    )
}

/// [`prepare_sha256_compression_batch_with_profile`] with an explicit
/// assignment layout for the BitZ opening (see [`Sha256OpeningLayout`]).
pub fn prepare_sha256_compression_batch_with_profile_and_layout<P: IopSecurityProfile>(
    log_compressions: usize,
    layout: Sha256OpeningLayout,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    // Gate the profile's opener target before any construction: the Ligerito
    // solver itself errors on out-of-range targets since the rate-1/2 default
    // work, which would otherwise mask this dedicated error.
    if !(64..=128).contains(&P::LIGERITO_TARGET_BITS) {
        return Err(Sha256ConstraintError::UnsupportedLigeritoTargetBits {
            actual: P::LIGERITO_TARGET_BITS,
        });
    }
    let instances = validate_batch_exponent(log_compressions)?;
    validate_instance_capacity(instances)?;
    let layout = if layout == Sha256OpeningLayout::Default && log_compressions < LOG_PACKING {
        let assignment_vars = packed_domain_vars(instances, SHA256_H_INSTANCE_BITS)?;
        Sha256OpeningLayout::InnerSumcheck {
            row_vars: single_forest_binary_params(assignment_vars).row_vars,
        }
    } else {
        layout
    };
    let prepared =
        prepare_sha256_compression_instances_with_profile_and_layout::<P>(instances, layout)?;
    let selection = crate::ligerito_flock::LigeritoSelection::for_target(
        prepared.security.ligerito_target_bits,
    );
    let prepared = prepared.with_ligerito(selection)?;
    validate_prepared_protocol(&prepared)?;
    Ok(prepared)
}

/// Controlled `2^14`-compression geometry used by the fixed-98-bit `t,s`
/// sweep. This is intentionally feature-gated and does not change the
/// production transcript-derived-prime profile.
#[cfg(feature = "bench-internals")]
pub fn prepare_sha256_compression_batch_for_product_t_fixed98(
    log_compressions: usize,
    product_t: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    if log_compressions != 14 || !(LOG_PACKING..=28).contains(&product_t) {
        return Err(Sha256ConstraintError::UnsupportedProductSweepGeometry {
            log_compressions,
            t: product_t,
        });
    }
    let instances = validate_batch_exponent(log_compressions)?;
    let prepared = prepare_sha256_compression_instances(
        instances,
        Sha256OpeningLayout::Default,
        Some(product_t),
        |_| Ok(fixed_98_security_params()),
        true,
    )?;
    let selection = crate::ligerito_flock::LigeritoSelection::for_target(
        prepared.security.ligerito_target_bits,
    );
    let prepared = prepared.with_ligerito(selection)?;
    validate_prepared_protocol(&prepared)?;
    if u128::from(*prepared.max_boolean_residual_bound()) >= SHA256_FIXED_98_PRIME {
        return Err(Sha256ConstraintError::FixedPrimeResidualBound);
    }
    Ok(prepared)
}

/// Prepares the largest packed batch whose assignment witness fits exactly
/// inside `2^log_assignment_rows` cells.
///
/// Each compression contributes [`SHA256_H_INSTANCE_BITS`] cells and the
/// entire batch shares one leading constant cell.  Any unused cells form one
/// trailing zero suffix; there is no per-instance padding. The resulting
/// next-power-of-two instance capacity must lie in the same supported window
/// as [`prepare_sha256_compression_batch`].
pub fn prepare_sha256_compression_batch_for_assignment_rows(
    log_assignment_rows: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    prepare_sha256_compression_batch_for_assignment_rows_with_profile::<Lambda100>(
        log_assignment_rows,
    )
}

/// [`prepare_sha256_compression_batch_for_assignment_rows`] under an explicit
/// security profile.
pub fn prepare_sha256_compression_batch_for_assignment_rows_with_profile<P: IopSecurityProfile>(
    log_assignment_rows: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    let rows = 1usize
        .checked_shl(
            u32::try_from(log_assignment_rows)
                .map_err(|_| Sha256ConstraintError::InvalidBatchExponent)?,
        )
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;
    let instances = rows
        .checked_sub(1)
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?
        / SHA256_H_INSTANCE_BITS;
    if instances == 0 {
        return Err(Sha256ConstraintError::InvalidBatchExponent);
    }
    validate_instance_capacity(instances)?;
    let prepared = prepare_sha256_compression_instances_with_profile::<P>(instances)?;
    let selection = crate::ligerito_flock::LigeritoSelection::for_target(
        prepared.security.ligerito_target_bits,
    );
    let prepared = prepared.with_ligerito(selection)?;
    validate_prepared_protocol(&prepared)?;
    if prepared.h_layout.row_vars + prepared.h_layout.col_vars != log_assignment_rows {
        return Err(Sha256ConstraintError::InvalidBatchExponent);
    }
    Ok(prepared)
}

#[cfg(test)]
pub(super) fn prepare_sha256_compression_batch_for_test(
    log_compressions: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    let instances = validate_batch_exponent(log_compressions)?;
    prepare_sha256_compression_instances_with_profile::<Lambda100>(instances)
}

#[cfg(test)]
pub(super) fn prepare_sha256_compression_batch_for_product_t_test(
    log_compressions: usize,
    product_t: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    let instances = 1usize
        .checked_shl(
            u32::try_from(log_compressions)
                .map_err(|_| Sha256ConstraintError::InvalidBatchExponent)?,
        )
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;
    prepare_sha256_compression_instances(
        instances,
        Sha256OpeningLayout::Default,
        Some(product_t),
        |facts| Lambda100::instantiate(facts).map_err(Sha256ConstraintError::from),
        false,
    )
}

fn prepare_sha256_compression_instances_with_profile<P: IopSecurityProfile>(
    instances: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    prepare_sha256_compression_instances_with_profile_and_layout::<P>(
        instances,
        Sha256OpeningLayout::Default,
    )
}

fn prepare_sha256_compression_instances_with_profile_and_layout<P: IopSecurityProfile>(
    instances: usize,
    layout: Sha256OpeningLayout,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    prepare_sha256_compression_instances(
        instances,
        layout,
        None,
        |facts| P::instantiate(facts).map_err(Sha256ConstraintError::from),
        false,
    )
}

fn prepare_sha256_compression_instances(
    instances: usize,
    mut layout: Sha256OpeningLayout,
    requested_product_t: Option<usize>,
    make_security: impl FnOnce(
        &super::super::profile::IopInstanceFacts,
    ) -> Result<IopSecurityParams, Sha256ConstraintError>,
    fixed_98: bool,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    let log_instance_capacity = instances
        .checked_next_power_of_two()
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?
        .ilog2() as usize;
    let exponent = u32::try_from(log_instance_capacity)
        .map_err(|_| Sha256ConstraintError::InvalidBatchExponent)?;
    let local = integer_local_relation();
    let source_vars = packed_domain_vars(instances, SHA256_F_INSTANCE_BITS)?;
    let assignment_vars = packed_domain_vars(instances, SHA256_H_INSTANCE_BITS)?;
    let f_layout = balanced_binary_params(source_vars);
    let local_bits = SHA256_H_BAR_LIVE_BITS.next_power_of_two().ilog2() as usize;
    // The production default opens the balanced `Id_{2^r} ⊗ M` block layout.
    // Resolving it here, before the geometry match, keeps the lift-arity and
    // forest-count rules below reading the layout that is actually opened.
    // The `t,s` sweep supplies its own split, so it keeps the legacy geometry.
    if layout == Sha256OpeningLayout::Default
        && requested_product_t.is_none()
        && instances.is_power_of_two()
    {
        layout = Sha256OpeningLayout::ProductTransposed {
            row_vars: balanced_product_row_vars(assignment_vars, local_bits, log_instance_capacity),
        };
    }
    let (h_layout, mut product_p_h, mut product_order) = match layout {
        Sha256OpeningLayout::Default => (
            single_forest_binary_params(assignment_vars),
            instances.is_power_of_two().then(|| {
                let t = log_instance_capacity.min(13);
                IntegerMatrixLayout {
                    row_vars: t,
                    col_vars: assignment_vars - t,
                    word_bits: 1,
                }
            }),
            PackedSourceOrder::LocalMajor,
        ),
        Sha256OpeningLayout::ProductTransposed { row_vars } => {
            if !instances.is_power_of_two() {
                return Err(Sha256ConstraintError::ProductLayoutNeedsPowerOfTwoBatch { instances });
            }
            if row_vars < local_bits || row_vars > local_bits + log_instance_capacity {
                return Err(Sha256ConstraintError::InvalidOpeningRowVars {
                    row_vars,
                    assignment_vars,
                });
            }
            (
                single_forest_binary_params(assignment_vars),
                Some(IntegerMatrixLayout {
                    row_vars: row_vars,
                    col_vars: assignment_vars - row_vars,
                    word_bits: 1,
                }),
                PackedSourceOrder::InstanceMajor,
            )
        }
        Sha256OpeningLayout::InnerSumcheck { row_vars } => {
            if row_vars < LOG_PACKING || row_vars >= assignment_vars {
                return Err(Sha256ConstraintError::InvalidOpeningRowVars {
                    row_vars,
                    assignment_vars,
                });
            }
            (
                IntegerMatrixLayout {
                    row_vars: row_vars,
                    col_vars: assignment_vars - row_vars,
                    word_bits: 1,
                },
                None,
                PackedSourceOrder::LocalMajor,
            )
        }
    };
    if let Some(t) = requested_product_t {
        if !instances.is_power_of_two()
            || t >= assignment_vars
            || (t > log_instance_capacity && t < local_bits)
        {
            return Err(Sha256ConstraintError::UnsupportedProductSweepGeometry {
                log_compressions: log_instance_capacity,
                t,
            });
        }
        product_p_h = Some(IntegerMatrixLayout {
            row_vars: t,
            col_vars: assignment_vars - t,
            word_bits: 1,
        });
        if t > log_instance_capacity {
            product_order = PackedSourceOrder::InstanceMajor;
            layout = Sha256OpeningLayout::ProductTransposed { row_vars: t };
        }
    }
    let map = PackedRepeatedVirtualMap::new(
        local.map.clone(),
        instances,
        h_layout.cells(),
        f_layout.cells(),
    )?;
    let product_map = product_p_h
        .map(|params| {
            PackedSourceRepeatedVirtualMap::new_with_order(
                local.map.clone(),
                instances,
                params.cells(),
                f_layout.cells(),
                product_order,
            )
        })
        .transpose()?;
    let mut facts = sha256_instance_facts(exponent);
    facts.opening_t = u32::try_from(product_p_h.unwrap_or(h_layout).row_vars)
        .map_err(|_| Sha256ConstraintError::InvalidBatchExponent)?;
    if layout != Sha256OpeningLayout::Default {
        // The opening's integer lift sums `2^t` terms. The production
        // layouts keep `t <= k`; an explicit split may not, so the no-wrap
        // arity follows the larger of the two.
        facts.lift_arity_log2 = facts.lift_arity_log2.max(facts.opening_t);
    }
    let security = make_security(&facts)?;
    let prime_profile = if fixed_98 {
        Sha256PrimeProfile::fixed_98(&security, log_instance_capacity)?
    } else {
        Sha256PrimeProfile::from_security(&security, log_instance_capacity)?
    };
    Ok(PreparedSha256CompressionBatch {
        local,
        map,
        product_map,
        product_p_h,
        f_layout,
        h_layout,
        instances,
        log_instance_capacity,
        security,
        ligerito: None, // Explicit algebra fixtures omit a production PCS policy.
        prime_profile,
        opening_layout: layout,
    })
}

fn validate_batch_exponent(log_compressions: usize) -> Result<usize, Sha256ConstraintError> {
    let instances = 1usize
        .checked_shl(
            u32::try_from(log_compressions)
                .map_err(|_| Sha256ConstraintError::InvalidBatchExponent)?,
        )
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;
    SHA256_H_INSTANCE_BITS
        .checked_mul(instances)
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;
    Ok(instances)
}

pub(super) fn validate_instance_capacity(instances: usize) -> Result<(), Sha256ConstraintError> {
    let log_instance_capacity = instances
        .checked_next_power_of_two()
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?
        .ilog2() as usize;
    if !(SHA256_MIN_LOG_COMPRESSIONS..=SHA256_MAX_LOG_COMPRESSIONS).contains(&log_instance_capacity)
    {
        return Err(Sha256ConstraintError::UnsupportedInstanceCapacityExponent {
            actual: log_instance_capacity,
        });
    }
    Ok(())
}

fn validate_prepared_protocol(
    prepared: &PreparedSha256CompressionBatch,
) -> Result<(), Sha256ConstraintError> {
    if prepared.prime_profile.is_fixed() {
        Sha256PrimeProfile::fixed_98(&prepared.security, prepared.log_instance_capacity)?;
    } else {
        Sha256PrimeProfile::from_security(&prepared.security, prepared.log_instance_capacity)?;
    }
    let max_q_bits =
        u128::BITS as usize - prepared.security.projection_max.leading_zeros() as usize;
    let opening_params = prepared.product_p_h.as_ref().unwrap_or(&prepared.h_layout);
    let forest_count = mod_q_num_chunks(opening_params, max_q_bits);
    let single_forest_required = prepared.prime_profile.is_fixed()
        || matches!(prepared.opening_layout, Sha256OpeningLayout::Default);
    if single_forest_required && forest_count != 1 {
        return Err(Sha256ConstraintError::UnsupportedOpeningForestCount {
            actual: forest_count,
        });
    }
    let target = prepared.security.ligerito_target_bits;
    if !(64..=128).contains(&target) {
        return Err(Sha256ConstraintError::UnsupportedLigeritoTargetBits { actual: target });
    }
    Ok(())
}

pub(super) fn packed_domain_vars(
    instances: usize,
    instance_width: usize,
) -> Result<usize, Sha256ConstraintError> {
    let live = instance_width
        .checked_mul(instances)
        .and_then(|cells| cells.checked_add(1))
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;
    let domain = live
        .checked_next_power_of_two()
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;
    Ok(domain.ilog2() as usize)
}

/// Splits one flat binary domain across BitZ rows and columns. The semantic
/// sequence stays `[1 | instance_0 | instance_1 | ... | trailing zeros]` and
/// is stored in BitZ's physical order: low `t` bits select a packed row and
/// high `s` bits select a column. The inner sumcheck uses that same index
/// order, so its terminal equality factors directly into `2^t` row weights
/// and `2^s` column weights. Keeping both factors near `2^(vars/2)` avoids
/// materializing a `2^vars` opening vector.
pub(super) const fn balanced_binary_params(vars: usize) -> IntegerMatrixLayout {
    let t = if vars.div_ceil(2) < LOG_PACKING {
        LOG_PACKING
    } else {
        vars.div_ceil(2)
    };
    IntegerMatrixLayout {
        row_vars: t,
        col_vars: vars - t,
        word_bits: 1,
    }
}

/// Splits the derived SHA assignment so every supported runtime-prime weight
/// fits in one BitZ chunk. The current SHA profiles use at most 113-bit primes;
/// with Bit cells, `t <= 127 - 113 - 1 = 13` makes the generic fold bound
/// strictly smaller than `2^127`. Shapes already balanced below that cap keep
/// their balanced layout.
const fn single_forest_binary_params(vars: usize) -> IntegerMatrixLayout {
    let balanced = balanced_binary_params(vars);
    if balanced.row_vars <= 13 {
        balanced
    } else {
        IntegerMatrixLayout {
            row_vars: 13,
            col_vars: vars - 13,
            word_bits: 1,
        }
    }
}

/// Row variables of the balanced `Id_{2^r} ⊗ M` product layout.
///
/// The virtualization matrix of a power-of-two batch is `Id_{2^k} ⊗ M`, one
/// local block `M` per compression. Opening it instance-major with
/// `t = local_bits + r` row variables groups the batch into `2^(k-r)` blocks of
/// `Id_{2^r} ⊗ M`, i.e. `2^r` compressions per grand product: `r` instance bits
/// join the local bits on the row axis and only the remaining `k - r` instance
/// bits index columns.
///
/// Without it the split is pinned at `t = min(k, 13)` with every local cell on
/// the column axis, so the read-off vector sent in the clear grows with the
/// local width rather than with the batch. `r` is chosen to land on the same
/// balance point the rest of the instantiation uses, `t = ceil(0.6 · n)`,
/// clamped to the range this layout can represent, `r in [0, k]`.
const fn balanced_product_row_vars(
    assignment_vars: usize,
    local_bits: usize,
    log_instance_capacity: usize,
) -> usize {
    let target = (3 * assignment_vars).div_ceil(5);
    if target < local_bits {
        local_bits
    } else if target > local_bits + log_instance_capacity {
        local_bits + log_instance_capacity
    } else {
        target
    }
}

fn integer_local_relation() -> &'static IntegerLocalRelation {
    INTEGER_LOCAL_RELATION.get_or_init(|| {
        build_integer_local_relation().expect("the static SHA-256 compression relation is valid")
    })
}

fn build_integer_local_relation() -> Result<IntegerLocalRelation, Sha256ConstraintError> {
    let mut generator = ConstraintGenerator::new(COMPRESSION_INPUT_BITS);
    let inputs = generator.inputs();
    let output = compression_circuit(&mut generator, &inputs);
    let generated = generator.into_matrices();

    assert_eq!(generated.m.row_count(), SHA256_H_BAR_LIVE_BITS);
    assert_eq!(generated.m.column_count(), SHA256_F_BAR_LIVE_BITS);
    assert_eq!(generated.a.row_count(), SHA256_CONSTRAINTS);
    assert_eq!(generated.b.row_count(), SHA256_CONSTRAINTS);
    assert_eq!(generated.c.row_count(), SHA256_CONSTRAINTS);
    assert_eq!(generated.a.column_count(), SHA256_H_BAR_LIVE_BITS);
    assert_eq!(generated.b.column_count(), SHA256_H_BAR_LIVE_BITS);
    assert_eq!(generated.c.column_count(), SHA256_H_BAR_LIVE_BITS);
    assert_eq!(circuit_matrix_nnz(&generated.a), 0);
    assert_eq!(circuit_matrix_nnz(&generated.b), 0);
    assert_eq!(generated.m.row(0).unwrap().indices(), &[0]);

    for word_slot in 0..SHA256_PUBLIC_WORDS {
        for bit in 0..SHA256_PUBLIC_WORD_BITS {
            let h_column = sha256_public_h_column(word_slot, bit);
            let f_column = sha256_public_f_column(word_slot, bit);
            assert_eq!(generated.m.row(h_column).unwrap().indices(), &[f_column]);

            if word_slot >= 24 {
                let output_bit = &output[(word_slot - 24) * SHA256_PUBLIC_WORD_BITS + bit];
                assert!(!output_bit.constant());
                assert_eq!(output_bit.witnesses().len(), 1);
                assert!(output_bit.witnesses().contains(&(f_column - 1)));
            }
        }
    }

    let native_rows = convert_native_integer_rows(&generated.c)?;
    let native_matrix = CscMatrix::try_from_rows(SHA256_H_BAR_LIVE_BITS, native_rows)
        .map_err(SpartanMatrixError::from)?;
    let linear_relation = Sha256LinearRelation { native_matrix };

    let map_rows = generated
        .m
        .rows()
        .map(|row| {
            row.indices()
                .iter()
                .copied()
                .map(|column| (column, true))
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>();
    let map = CscMatrix::try_from_rows(SHA256_F_BAR_LIVE_BITS, map_rows)
        .map_err(SpartanMatrixError::from)?;
    let map = PreparedVirtualMap::new(map)?;
    let max_boolean_residual_bound =
        max_boolean_linear_residual_bound(&linear_relation.native_matrix);
    let digest = integer_relation_digest(&linear_relation.native_matrix, &map)?;

    Ok(IntegerLocalRelation {
        linear_relation,
        map,
        digest,
        max_boolean_residual_bound,
    })
}

pub(super) fn circuit_matrix_nnz(matrix: &CsrMatrix<IntegerTable>) -> usize {
    matrix.nnz()
}

pub(super) fn convert_native_integer_rows(
    matrix: &CsrMatrix<IntegerTable>,
) -> Result<Vec<Vec<(usize, i64)>>, Sha256ConstraintError> {
    (0..matrix.row_count())
        .map(|row| {
            matrix
                .row(row)
                .unwrap()
                .iter()
                .map(|(column, coefficient)| (column, coefficient.as_words()))
                .map(|(column, words)| {
                    let value = words[0] as i64;
                    let extension = if value < 0 { u64::MAX } else { 0 };
                    if words[1..].iter().all(|&word| word == extension) {
                        Ok((column, value))
                    } else {
                        Err(Sha256ConstraintError::IntegerRelationTooLarge)
                    }
                })
                .collect::<Result<Vec<_>, _>>()
        })
        .collect()
}

#[allow(dead_code)]
fn project_signed_matrix(
    matrix: &CscMatrix<Box<[i64]>>,
    field_config: &<SpartanBitzField as crate::piop::spartan::SpartanField>::Config,
) -> Result<CscMatrix<Box<[SpartanBitzField]>>, SpartanMatrixError> {
    let field = crate::piop::spartan::raw_monty::field_context(field_config);
    let columns = matrix
        .columns()
        .map(|column| {
            column
                .into_iter()
                .map(|(row, coefficient)| (row, field.from_integer(coefficient)))
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>();
    CscMatrix::try_from_columns(matrix.row_count(), columns).map_err(SpartanMatrixError::from)
}

pub(super) fn max_boolean_linear_residual_bound(matrix: &CscMatrix<Box<[i64]>>) -> field::Uint<2> {
    let mut sums = vec![field::Uint::<2>::ZERO; matrix.row_count()];
    for column in matrix.columns() {
        for (row, coefficient) in column {
            let next = sums[row].checked_add_ct(&field::Uint::from_u64(coefficient.unsigned_abs()));
            assert!(
                next.validity().declassify(),
                "public SHA row norm exceeds two limbs"
            );
            sums[row] = *next.value();
        }
    }
    sums.into_iter()
        .max_by_key(|value| u128::from(*value))
        .unwrap_or_default()
}

fn integer_relation_digest(
    matrix: &CscMatrix<Box<[i64]>>,
    map: &PreparedVirtualMap,
) -> Result<[u8; 32], Sha256ConstraintError> {
    let mut hash = Hasher::new();
    hash.update(b"bitz/sha256/flat-linear-relation/v3");
    hash.update(&map.digest());
    hash.update(b"C");
    for value in [matrix.row_count(), matrix.column_count(), matrix.nnz()] {
        hash_usize(&mut hash, value)?;
    }
    for column in matrix.columns() {
        hash_usize(&mut hash, column.len())?;
        for (row, coefficient) in column {
            hash_usize(&mut hash, row)?;
            hash.update(&coefficient.to_le_bytes());
        }
    }
    Ok(*hash.finalize().as_bytes())
}

pub(super) fn hash_usize(hash: &mut Hasher, value: usize) -> Result<(), Sha256ConstraintError> {
    hash.update(
        &u64::try_from(value)
            .map_err(|_| Sha256ConstraintError::IntegerRelationTooLarge)?
            .to_le_bytes(),
    );
    Ok(())
}

#[cfg(test)]
mod tests {

    use crate::pcs::FQ_MOD;
    use crate::piop::spartan::profile::PrimePolicy;
    use circuit::linear_map::binary::VirtualMap;

    use super::*;

    const OTHER_TEST_PRIME: u128 = (1_u128 << 127) - 1;

    fn config(modulus: u128) -> <Fp<2> as crate::piop::spartan::SpartanField>::Config {
        Fp::<2>::make_cfg(&Uint::from(modulus)).expect("odd test modulus")
    }

    #[test]
    fn local_relation_has_the_freigen_geometry() {
        let prepared = prepare_sha256_compression_batch_for_test(3).unwrap();
        let linear = prepared.linear_relation();
        let map = prepared.map();
        let f_layout = prepared.source_params();
        let h_layout = prepared.assignment_params();
        assert_eq!(linear.row_count(), SHA256_CONSTRAINTS);
        assert_eq!(linear.column_count(), SHA256_H_BAR_LIVE_BITS);
        assert!(linear.nnz() > 0);
        assert_eq!(linear.native_matrix().row_count(), SHA256_CONSTRAINTS);
        assert_eq!(
            linear.native_matrix().column_count(),
            SHA256_H_BAR_LIVE_BITS
        );
        assert_eq!(map.local().rows(), SHA256_H_BAR_LIVE_BITS);
        assert_eq!(map.local().cols(), SHA256_F_BAR_LIVE_BITS);
        assert_eq!(map.live_rows(), 1 + 8 * SHA256_H_INSTANCE_BITS);
        assert_eq!(map.live_cols(), 1 + 8 * SHA256_F_INSTANCE_BITS);
        assert_eq!(map.rows(), 1 << 18);
        assert_eq!(map.cols(), 1 << 16);
        assert_eq!(
            *f_layout,
            IntegerMatrixLayout {
                row_vars: 8,
                col_vars: 8,
                word_bits: 1
            }
        );
        assert_eq!(
            *h_layout,
            IntegerMatrixLayout {
                row_vars: 9,
                col_vars: 9,
                word_bits: 1
            }
        );
    }

    #[test]
    fn generated_r1cs_is_exactly_the_signed_linear_c_relation() {
        let mut generator = ConstraintGenerator::new(COMPRESSION_INPUT_BITS);
        let inputs = generator.inputs();
        let _ = compression_circuit(&mut generator, &inputs);
        let generated = generator.into_matrices();

        assert_eq!(circuit_matrix_nnz(&generated.a), 0);
        assert_eq!(circuit_matrix_nnz(&generated.b), 0);
        assert_eq!(generated.c.row_count(), SHA256_CONSTRAINTS);
        assert_eq!(generated.c.column_count(), SHA256_H_BAR_LIVE_BITS);

        let exact_c = CscMatrix::try_from_rows(
            generated.c.column_count(),
            convert_native_integer_rows(&generated.c).unwrap(),
        )
        .unwrap();
        let prepared = prepare_sha256_compression_batch_for_test(0).unwrap();
        assert_eq!(prepared.linear_relation().matrix(), &exact_c);
    }

    #[test]
    fn flat_linear_coordinates_have_no_per_instance_padding() {
        let prepared = prepare_sha256_compression_batch_for_test(2).unwrap();
        assert_eq!(prepared.instances(), 4);
        assert_eq!(prepared.linear_row_count(), 4 * SHA256_CONSTRAINTS);
        assert_eq!(
            prepared.linear_assignment_column_count(),
            1 + 4 * SHA256_H_INSTANCE_BITS
        );

        for instance in 0..prepared.instances() {
            for local_row in [0, 1, SHA256_CONSTRAINTS - 1] {
                assert_eq!(
                    prepared.flat_constraint_row(instance, local_row),
                    Some(SHA256_CONSTRAINTS * instance + local_row)
                );
            }
            assert_eq!(prepared.flat_assignment_column(instance, 0), Some(0));
            for local_column in [1, 2, SHA256_H_BAR_LIVE_BITS - 1] {
                assert_eq!(
                    prepared.flat_assignment_column(instance, local_column),
                    Some(1 + instance * SHA256_H_INSTANCE_BITS + local_column - 1)
                );
            }
        }

        for instance in 0..prepared.instances() - 1 {
            assert_eq!(
                prepared
                    .flat_constraint_row(instance, SHA256_CONSTRAINTS - 1)
                    .unwrap()
                    + 1,
                prepared.flat_constraint_row(instance + 1, 0).unwrap()
            );
            assert_eq!(
                prepared
                    .flat_assignment_column(instance, SHA256_H_BAR_LIVE_BITS - 1)
                    .unwrap()
                    + 1,
                prepared.flat_assignment_column(instance + 1, 1).unwrap()
            );
        }

        assert_eq!(prepared.flat_constraint_row(4, 0), None);
        assert_eq!(prepared.flat_constraint_row(0, SHA256_CONSTRAINTS), None);
        assert_eq!(prepared.flat_assignment_column(4, 0), None);
        assert_eq!(
            prepared.flat_assignment_column(0, SHA256_H_BAR_LIVE_BITS),
            None
        );
    }

    #[test]
    fn repeated_map_preserves_instance_coordinates() {
        let prepared = prepare_sha256_compression_batch_for_test(2).unwrap();
        let map = prepared.map();
        let instances = 4;
        for local_column in [1, SHA256_F_BAR_LIVE_BITS - 1] {
            let local_rows = map
                .local()
                .matrix()
                .column(local_column)
                .unwrap()
                .indices()
                .to_vec();
            for instance in 0..instances {
                let global_column = 1 + instance * SHA256_F_INSTANCE_BITS + local_column - 1;
                let global_rows = map.column_rows(global_column).unwrap().collect::<Vec<_>>();
                assert_eq!(
                    global_rows,
                    local_rows
                        .iter()
                        .map(|row| {
                            if *row == 0 {
                                0
                            } else {
                                1 + instance * SHA256_H_INSTANCE_BITS + row - 1
                            }
                        })
                        .collect::<Vec<_>>()
                );
            }
        }

        let constant_rows = map.column_rows(0).unwrap().collect::<Vec<_>>();
        let expected_constant_rows = map
            .local()
            .matrix()
            .column(0)
            .unwrap()
            .indices()
            .iter()
            .flat_map(|&row| {
                if row == 0 {
                    vec![0]
                } else {
                    (0..instances)
                        .map(|instance| 1 + instance * SHA256_H_INSTANCE_BITS + row - 1)
                        .collect()
                }
            })
            .collect::<Vec<_>>();
        assert_eq!(constant_rows, expected_constant_rows);
    }

    #[test]
    fn assignment_row_sizing_fills_one_global_domain_without_instance_padding() {
        let log_rows = 21;
        let prepared = prepare_sha256_compression_batch_for_assignment_rows(log_rows).unwrap();
        let domain = 1usize << log_rows;
        let instances = (domain - 1) / SHA256_H_INSTANCE_BITS;

        assert_eq!(instances, 102);
        assert_eq!(prepared.instances(), instances);
        assert_eq!(prepared.log_instance_capacity(), 7);
        assert_eq!(prepared.assignment_params().cells(), domain);
        assert_eq!(
            *prepared.assignment_params(),
            IntegerMatrixLayout {
                row_vars: 11,
                col_vars: 10,
                word_bits: 1,
            }
        );
        assert_eq!(
            prepared.map().live_rows(),
            1 + instances * SHA256_H_INSTANCE_BITS
        );
        assert_eq!(
            prepared.map().live_cols(),
            1 + instances * SHA256_F_INSTANCE_BITS
        );
        assert!(domain - prepared.map().live_rows() < SHA256_H_INSTANCE_BITS);
        assert!(
            prepared
                .map()
                .column_rows(prepared.map().live_cols())
                .unwrap()
                .next()
                .is_none()
        );
    }

    #[test]
    fn production_assignment_geometry_uses_one_forest() {
        for exponent in 7..=SHA256_MAX_LOG_COMPRESSIONS {
            let prepared = prepare_sha256_compression_batch(exponent).unwrap();
            let max_q_bits =
                u128::BITS as usize - prepared.security().projection_max.leading_zeros() as usize;
            assert_eq!(
                mod_q_num_chunks(prepared.assignment_params(), max_q_bits),
                1,
                "log-compressions={exponent}"
            );
            if exponent >= 10 {
                assert_eq!(
                    *prepared.assignment_params(),
                    IntegerMatrixLayout {
                        row_vars: 13,
                        col_vars: exponent + 2,
                        word_bits: 1,
                    },
                    "log-compressions={exponent}"
                );
            }
        }

        let prepared = prepare_sha256_compression_batch(14).unwrap();
        // The balanced `Id_{2^r} ⊗ M` opening lifts `2^t` terms rather than
        // `2^min(k,13)`, so the no-wrap bound narrows the prime accordingly.
        assert_eq!(
            u128::BITS as usize - prepared.security().projection_max.leading_zeros() as usize,
            110
        );
    }

    /// The production layout is the balanced `Id_{2^r} ⊗ M` block tensor: the
    /// local bits plus `r` instance bits form the rows, so the read-off vector
    /// sent in the clear is indexed by the remaining `k - r` instance bits and
    /// stops growing with the local width.
    #[test]
    fn production_opening_is_the_balanced_id_tensor_block_layout() {
        for exponent in LOG_PACKING..=SHA256_MAX_LOG_COMPRESSIONS {
            let prepared = prepare_sha256_compression_batch(exponent).unwrap();
            let local_bits = SHA256_H_BAR_LIVE_BITS.next_power_of_two().ilog2() as usize;
            let assignment_vars = local_bits + exponent;
            let opening = prepared.opening_params();
            assert_eq!(
                prepared.opening_layout(),
                Sha256OpeningLayout::ProductTransposed {
                    row_vars: opening.row_vars
                },
                "log-compressions={exponent}"
            );
            assert_eq!(
                prepared.product_map().unwrap().order(),
                PackedSourceOrder::InstanceMajor,
                "log-compressions={exponent}"
            );
            assert_eq!(opening.row_vars + opening.col_vars, assignment_vars);
            // `r in [0, k]`, landing on `ceil(0.6 n)` wherever that is
            // representable.
            let r = opening.row_vars - local_bits;
            assert!(r <= exponent, "log-compressions={exponent}");
            assert_eq!(
                opening.row_vars,
                (3 * assignment_vars)
                    .div_ceil(5)
                    .clamp(local_bits, local_bits + exponent),
                "log-compressions={exponent}"
            );
        }
    }

    #[cfg(feature = "bench-internals")]
    #[test]
    fn fixed_98_sweep_preserves_geometry_and_single_forest_bound() {
        for t in 7..=28 {
            let prepared = prepare_sha256_compression_batch_for_product_t_fixed98(14, t).unwrap();
            let params = prepared.product_assignment_params().unwrap();
            assert_eq!(
                (params.row_vars, params.col_vars, params.word_bits),
                (t, 29 - t, 1)
            );
            assert_eq!(prepared.instances(), 1 << 14);
            assert_eq!(prepared.security().projection_min, SHA256_FIXED_98_PRIME);
            assert!(prepared.prime_profile().is_fixed());
            assert_eq!(mod_q_num_chunks(params, 98), 1);
            assert_eq!(
                prepared.product_map().unwrap().order(),
                if t <= 14 {
                    PackedSourceOrder::LocalMajor
                } else {
                    PackedSourceOrder::InstanceMajor
                },
            );
        }
        for (k, t) in [(13, 13), (15, 13), (14, 6), (14, 29)] {
            assert!(matches!(
                prepare_sha256_compression_batch_for_product_t_fixed98(k, t),
                Err(Sha256ConstraintError::UnsupportedProductSweepGeometry { .. })
            ));
        }
    }

    #[test]
    fn public_preparation_rejects_unsupported_instance_capacities() {
        for exponent in [3, 17] {
            assert!(matches!(
                prepare_sha256_compression_batch(exponent),
                Err(Sha256ConstraintError::UnsupportedInstanceCapacityExponent {
                    actual
                }) if actual == exponent
            ));
        }

        assert!(matches!(
            prepare_sha256_compression_batch_for_assignment_rows(17),
            Err(Sha256ConstraintError::UnsupportedInstanceCapacityExponent { actual: 3 })
        ));
        assert!(matches!(
            prepare_sha256_compression_batch_for_assignment_rows(31),
            Err(Sha256ConstraintError::UnsupportedInstanceCapacityExponent { actual: 17 })
        ));
    }

    #[test]
    fn public_preparation_rejects_profiles_the_sha_backend_cannot_use() {
        struct OversizedLigeritoTarget;
        impl IopSecurityProfile for OversizedLigeritoTarget {
            const NAME: &'static str = "oversized-ligerito-target-test";
            const LAMBDA: u32 = 100;
            const PRIME_POLICY: PrimePolicy = PrimePolicy::SingleDerived;
            const LIGERITO_TARGET_BITS: usize = 129;
            const FOREST_ROUND_GRINDING_BITS: u32 = 0;
            const RING_SWITCH_GRINDING_BITS: u32 = 0;
        }

        struct TwoPrimeShaProfile;
        impl IopSecurityProfile for TwoPrimeShaProfile {
            const NAME: &'static str = "two-prime-sha-test";
            const LAMBDA: u32 = 100;
            const PRIME_POLICY: PrimePolicy = PrimePolicy::TwoFullWidthFingerprint;
            const LIGERITO_TARGET_BITS: usize = 100;
            const FOREST_ROUND_GRINDING_BITS: u32 = 0;
            const RING_SWITCH_GRINDING_BITS: u32 = 0;
        }

        assert!(matches!(
            prepare_sha256_compression_batch_with_profile::<OversizedLigeritoTarget>(7),
            Err(Sha256ConstraintError::UnsupportedLigeritoTargetBits { actual: 129 })
        ));
        assert!(matches!(
            prepare_sha256_compression_batch_with_profile::<TwoPrimeShaProfile>(7),
            Err(Sha256ConstraintError::PrimeProfile(
                Sha256PrimeError::ProfileStrategyMismatch
            ))
        ));
    }

    #[test]
    fn public_statement_layout_matches_the_local_map() {
        let prepared = prepare_sha256_compression_batch_for_test(0).unwrap();
        let map = prepared.map();
        let mut sources_by_h = vec![Vec::new(); map.local().matrix().row_count()];
        for (f_column, column) in map.local().matrix().columns().enumerate() {
            for &h_column in column.indices() {
                sources_by_h[h_column].push(f_column);
            }
        }

        for word_slot in 0..SHA256_PUBLIC_WORDS {
            for bit in 0..SHA256_PUBLIC_WORD_BITS {
                let h_column = sha256_public_h_column(word_slot, bit);
                let f_column = sha256_public_f_column(word_slot, bit);
                assert_eq!(sources_by_h[h_column], [f_column]);
            }
        }
    }

    #[test]
    fn exact_linear_relation_projects_under_distinct_runtime_primes() {
        let prepared = prepare_sha256_compression_batch_for_test(0).unwrap();
        let fixed_config = config(FQ_MOD);
        let other_config = config(OTHER_TEST_PRIME);
        let fixed = prepared.project_linear_relation(&fixed_config).unwrap();
        let other = prepared.project_linear_relation(&other_config).unwrap();

        assert_eq!(fixed.matrix().row_count(), SHA256_CONSTRAINTS);
        assert_eq!(fixed.matrix().column_count(), SHA256_H_BAR_LIVE_BITS);
        assert_eq!(
            SpartanBitzField::canonical_modulus_encoding(fixed.config()),
            SpartanBitzField::canonical_modulus_encoding(&fixed_config)
        );
        assert_eq!(
            SpartanBitzField::canonical_modulus_encoding(other.config()),
            SpartanBitzField::canonical_modulus_encoding(&other_config)
        );

        for ((raw_column, fixed_column), other_column) in prepared
            .linear_relation()
            .matrix()
            .columns()
            .zip(fixed.matrix().columns())
            .zip(other.matrix().columns())
        {
            assert_eq!(raw_column.indices(), fixed_column.indices());
            assert_eq!(raw_column.indices(), other_column.indices());
            for ((raw, fixed), other) in raw_column
                .coefficients()
                .iter()
                .zip(fixed_column.coefficients())
                .zip(other_column.coefficients())
            {
                assert_eq!(
                    fixed,
                    &crate::piop::spartan::raw_monty::field_context(&fixed_config)
                        .from_integer(raw)
                );
                assert_eq!(
                    other,
                    &crate::piop::spartan::raw_monty::field_context(&other_config)
                        .from_integer(raw)
                );
            }
        }
    }

    #[test]
    fn boolean_residual_bound_is_below_the_smallest_production_prime() {
        let prepared = prepare_sha256_compression_batch_for_test(0).unwrap();
        assert!(u128::from(*prepared.max_boolean_residual_bound()) < (1u128 << 111));
    }
}
